# Generated by Django 3.2.25 on 2024-09-24 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoURL', models.URLField(help_text='The URL of the photo for the loan profile.')),
                ('title', models.CharField(help_text='The title of the loan profile.', max_length=255)),
                ('description', models.TextField(help_text='The description of the loan profile.')),
                ('business_type', models.CharField(help_text='The type of business for the loan profile.', max_length=255)),
                ('loan_duration_months', models.IntegerField(default=12, help_text='The duration of the loan in months.')),
                ('total_amount_required', models.DecimalField(decimal_places=2, help_text='The total amount required for the loan.', max_digits=10)),
                ('deadline_to_receive_loan', models.DateField(default=datetime.datetime(2025, 9, 24, 6, 41, 46, 792931, tzinfo=utc), help_text='The deadline to receive the loan.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the loan profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the loan profile was last updated.')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1, help_text='The status of the loan profile.')),
            ],
            options={
                'verbose_name': 'Loan Profile',
                'verbose_name_plural': 'Loan Profiles',
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text="The name of the user's business, if applicable.", max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, help_text="The user's business type.", max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, help_text='The city where the user is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country where the user is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the user was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='The interests of the user.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AddField(
            model_name='user',
            name='photoURL',
            field=models.URLField(blank=True, help_text="The URL of the user's photo."),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('lender', 'Lender'), ('borrower', 'Borrower'), ('admin', 'Admin')], default='borrower', help_text='The role of the user in the system.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='story',
            field=models.TextField(blank=True, help_text='The personal story of the user.'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the user was last updated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the user.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='The full name of the user.', max_length=255),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount for the transaction.', max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now=True, help_text='The date and time when the transaction occurred.')),
                ('payment_method', models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Debit Card'), (3, 'PayPal'), (4, 'Apple Pay'), (5, 'Google Pay'), (6, 'Bank Transfer'), (7, 'Cash'), (8, 'Cryptocurrency')], default=3, help_text='The method of payment for the transaction.')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed'), (4, 'Refunded'), (5, 'Canceled'), (6, 'On Hold'), (7, 'Chargeback')], default=1, help_text='The status of the transaction.')),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.loanprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='user',
            field=models.ForeignKey(help_text='The user associated with the loan profile.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
