# Generated by Django 3.2.25 on 2024-10-05 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240928_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 10, 5, 3, 9, 35, 123817, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
