# Generated by Django 3.2.25 on 2024-10-06 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loanprofile_deadline_to_receive_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 10, 6, 22, 16, 50, 780780, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
        migrations.CreateModel(
            name='LoanUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.IntegerField(choices=[(1, 'Progress Update'), (2, 'Milestone Update'), (3, 'Delay Update'), (4, 'Cancellation Update'), (5, 'Completion Update')], default=1, help_text='The type of update for the loan profile.')),
                ('update_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.loanprofile')),
            ],
        ),
    ]
