# Generated by Django 3.2.25 on 2024-09-14 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240914_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoURL', models.URLField(help_text='The URL of the photo for the loan profile.')),
                ('description', models.TextField(help_text='The description of the loan profile.')),
                ('business_type', models.IntegerField(help_text='The type of business for the loan profile.')),
                ('loan_duration_months', models.IntegerField(help_text='The duration of the loan in months.')),
                ('total_amount_required', models.DecimalField(decimal_places=2, help_text='The total amount required for the loan.', max_digits=10)),
                ('amount_lended_to_date', models.DecimalField(decimal_places=2, help_text='The amount lended to date for the loan.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the loan profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the loan profile was last updated.')),
                ('user', models.OneToOneField(help_text='The user associated with the loan profile.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Profile',
                'verbose_name_plural': 'Loan Profiles',
                'ordering': ['user'],
            },
        ),
    ]
