# Generated by Django 3.2.25 on 2024-10-07 00:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241006_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanupdate',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Loan Updte', 'verbose_name_plural': 'Loan Updates'},
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 0, 9, 25, 622902, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
