# Generated by Django 3.2.25 on 2024-09-14 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loanprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_category',
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=django.utils.timezone.now, help_text='The deadline to receive the loan.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Funded'), (3, 'Rejected')], default=1, help_text='The status of the loan profile.'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, help_text="The user's business type.", max_length=255),
        ),
    ]
