# Generated by Django 3.2.25 on 2024-10-07 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241007_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 0, 12, 39, 514649, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
    ]
