# Generated by Django 3.2.25 on 2024-09-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240914_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='business_type',
            field=models.CharField(help_text='The type of business for the loan profile.', max_length=255),
        ),
    ]
