# Generated by Django 3.2.25 on 2024-09-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_loanprofile_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='user',
            field=models.ForeignKey(help_text='The user associated with the loan profile.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
