# Generated by Django 3.2.25 on 2024-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_loanprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprofile',
            name='title',
            field=models.CharField(default='Default', help_text='The title of the loan profile.', max_length=255),
            preserve_default=False,
        ),
    ]
