# Generated by Django 3.2.25 on 2024-09-24 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_loanprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprofile',
            name='amount_lended_to_date',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount lended to date for the loan.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='deadline_to_receive_loan',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 2, 25, 46, 243455, tzinfo=utc), help_text='The deadline to receive the loan.'),
        ),
        migrations.AlterField(
            model_name='loanprofile',
            name='loan_duration_months',
            field=models.IntegerField(default=12, help_text='The duration of the loan in months.'),
        ),
    ]
